parameters:
#    dwozniak_openshift.example.class: Dwozniak\OpenshiftBundle\Example

services:
#    dwozniak_openshift.example:
#        class: %dwozniak_openshift.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
